version: '3'

services:

  app:
    hostname: app
    build: './src/app'
    volumes:
      - './src/app:/app'

  docker-push:
    image: 'tmvdl/projects:flet'
    build: './src/app'

  github-release:
    image: 'github-release'
    build: './src'
