name: GitHub release

on:
  schedule:
    - cron: '50 23 * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  artifacts:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Docker build
        run: docker-compose build app

      - name: Export app
        run: docker run -v $(pwd)/dist:/dist app ls -laR
